baseURL = 'https://www.stefanheinze.com'
languageCode = 'en-us'
title = 'Stefan Heinze'
theme = "beautifulhugo"
googleAnalytics = "G-335S8PJ1KX"

[Params]
    subtitle = "Data Scientist | New York City, New York"
    logo = "/images/Stefan.jpeg"
    topleft = ""

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2

[[menu.main]]
    name = "Links"
    url = "/links"
    weight = 3

[Author]
  name = "Stefan Heinze"
  website = "https://www.stefanheinze.com"
  linkedin = "stefangheinze"
  github = "sgheinze12"
  email = "stefan.g.heinze@gmail.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true