baseURL = 'https://www.stefanheinze.com'
languageCode = 'en-us'
title = 'Stefan Heinze'
theme = "beautifulhugo"

[Params]
    subtitle = "Data Science"
    logo = "/images/Stefan.jpeg"

[[menu.main]]
    name = "About"
    url = ""
    weight = 1

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2

[[menu.main]]
    name = "Resume"
    url = ""
    weight = 3

[Author]
  name = "Stefan Heinze"
  website = "www.stefanheinze.com"
  linkedin = "stefangheinze"
  github = "sgheinze12"